### ISSUE TITLE
How to display step counter labels?

### ISSUE THREAD

**Issue by kibotu** [amcolash/MMM-GoogleFit#5]
can't find the respective setting, the step counter shown in the screenshots is not being displayed by default. am i missing something?

**Comment by fry0815** [comment]
I thought the same but it is not the the step counter, it is the weight ;)
A step counter would be nice. :)

**Comment by amcolash** [comment]
Ah yes you are correct. The number is the weights (I have a smart scale, so I added that feature). Since there is not a lot of real estate between the values, I could add something like "4.4k" instead of listing out 4,431. Or I could even round to "4k" and give how many 1,000 steps as a rough guesstimate. Once you get above 10k, the extra decimal becomes less useful.

Thoughts?
I like showing decimal below 10k (1.5k), then just round to nearest above that so 12,100 would be 12k, 12,900 would be 13k

**Comment by amcolash** [comment]
Added in a new commit which allows for the step count label to be shown, open a terminal:
`$ cd MagicMirror/modules/MMM-GoogleFit`
`$ git pull`
To update the module.

Let me know what you both think and if there are improvements you might want to see.

Speaking of steps - I need to go on a run this weekend :wink:

![image](https://user-images.githubusercontent.com/8282413/36885741-67243066-1dae-11e8-8ace-c5f454b078cc.png)

**Comment by kibotu** [comment]
awesome! just tried it out, lgtm :) thanks a lot!

**Comment by amcolash** [comment]
Great to hear. I am going to close this issue up for now then. Thanks for the feedback!
